### PR TITLE
Added a pull request template

### PR DESCRIPTION
**Pull request by javiergonzper**

### CODE REVIEW

**Comment by michaelstingl** [comment]
@javiergonzper [owncloud/core/.github/PULL_REQUEST_TEMPLATE.md](https://github.com/owncloud/core/blob/master/.github/PULL_REQUEST_TEMPLATE.md) is more fancy. Something we could borrow?

**Comment by DeepDiver1975** [comment]
And people .... please .... https://twitter.com/gitlab/status/1006245935675006977

**Comment by javiergonzper** [comment]
@michaelstingl uhm... yes I think that we could part of the checkboxes 👍 I will check them and add here and on the PR template of the app

**Comment by javiergonzper** [comment]
@michaelstingl I think that the Core PR template it is more complete than ours. We should use that document (also in my opinion it is better use the same documentation along the ownCloud project).

**Comment by michaelstingl** [comment]
@javiergonzper If some things doesn't apply for us, then we shouldn't us it, but same structure everywhere sounds great!

**Comment by javiergonzper** [comment]
@michaelstingl I made small modifications on the document (very small).
In my opinion all apply if we take into account that the idea of this file it is mostly for external pull requests (of course also for ours).

@DeepDiver1975 I read the link and was very useful, thanks again 👍

**Pull request merged**
